
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ThemeProviderWrapper from "@/theme/ThemeProviderWrapper";
import React from "react";
import "./globals.css";
import { Box, Container } from "@mui/material";
import { urbanist } from "./fonts"; 
import Menu from "./components/Menu"

import { PathWithMenu } from "@/lib/utils/pathMenu";
import CheckOverflow from "@/lib/utils/checkOverflow";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
  notContainer
}: Readonly<{
  children: React.ReactNode;
  notContainer?: boolean
}>) {

  
  return (
    <html lang="en" style={{ display: "flex", justifyContent: "center" }}     className={urbanist.variable} >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProviderWrapper>
          <div style={{ width: "360px", height: "100vh", background: "rgba(244, 244, 244, 1)", overflowX: "hidden", position: "relative" }}>
            <CheckOverflow>
              <Providers>
                 {children}
              </Providers>
            </CheckOverflow>
            <PathWithMenu />
          </div>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
